apiVersion: v1
kind: Service
metadata:
  name: wazo-ring
  namespace: ngrok-ingress-controller
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: wazo-ring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazo-ring
  namespace: ngrok-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazo-ring
  template:
    metadata:
      labels:
        app: wazo-ring
    spec:
      containers:
        - name: wazoring
          image: quintana/wazoring:latest
          ports:
            - name: http
              containerPort: 80
---
# ngrok Ingress Controller Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wazo-ring-ingress
  namespace: ngrok-ingress-controller
spec:
  ingressClassName: ngrok
  rules:
    - host: ring.quintana.ngrok.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wazo-ring
                port:
                  number: 80
